### ISSUE TITLE
[refactor] Master Refactor Checklist

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/docs#3]
- [ ] Styling - @elvece
- [ ] Versioning? - @kn0wmad investigating 
- [ ] Domains - @elvece 
    - [ ] docs.start9.com
    - [ ] dev-docs.start9.com
    - [ ] versioned?
- [ ] CI/CD?
- [ ] Deployment - @elvece 
- [ ] Content (Docs) - @kn0wmad and team
    - [ ] Introduction
    - [ ] User Manual
        - [ ] Initial Setup
        - [ ] Backup & Restore
            - [ ] Cloud
            - [ ] Remote
            - [ ] Local Network
            - [ ] Physical
            - [ ] Restore from Backup
                - [ ] Restore
                - [ ] Attach
                - [ ] Recover
                - [ ] Transfer
                - [ ] Hardware upgrades
        - [ ] StartOS Walkthrough
            - [ ] Main UI
            - [ ] Updates
            - [ ] Managing Services
            - [ ] Customization
            - [ ] Session Management
            - [ ] WiFi & Bluetooth
            - [ ] SSH
            - [ ] Marketplace
                - [ ] Managing registries
    
    - [ ] Support
        - [ ] FAQ
        - [ ] Troubleshooting
            - [ ] Initial setup
            - [ ] Device connectivity
            - [ ] Backups
            - [ ] Reset your password
        - [ ] Start9 Support
        - [ ] External Support
    - [ ] Guides
        - [ ] DIY
            - [ ] X86_64
            - [ ] RasPi
            - [ ] ARM
        - [ ] Device Guides
            - [ ] Linux
                - [ ] LAN
                - [ ] VPN
                - [ ] Domains
                - [ ] Tor
                - [ ] Browser config
            - [ ] Mac
                - [ ] LAN
                - [ ] VPN
                - [ ] Domains
                - [ ] Tor
                - [ ] Browser config
            - [ ] Windows
                - [ ] LAN
                - [ ] VPN
                - [ ] Domains
                - [ ] Tor
                - [ ] Browser config
            - [ ] Android
                - [ ] LAN
                - [ ] VPN
                - [ ] Domains
                - [ ] Tor
                - [ ] Browser config
            - [ ] iOS
                - [ ] LAN
                - [ ] VPN
                - [ ] Domains
                - [ ] Tor
                - [ ] Browser config
        - [ ] Service guides
            - [ ] Bitcoin
            - [ ] Jellyfin
            - [ ] Lightning
            - [ ] Matrix
            - [ ] Nextcloud
            - [ ] Specter
            - [ ] Vaultwarden

- [ ] Content (Dev docs) - @MattDHill and team
    - [ ] Contributing
        - [ ] StartOS
        - [ ] Service packaging
        - [ ] Documentation
    - [ ] StartOS Dev Tools
        - [ ] startd
        - [ ] start-cli
        - [ ] start-sdk
    - [ ] Package A Service
    - [ ] Packaging Spec
    - [ ] Submission Process
